version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: monorepo-api-dev
    environment:
      - APP_ENV=development
      - PORT=8000
      - LOG_LEVEL=debug
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - api_dev_cache:/app/.venv
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: monorepo-client-dev
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
      - "24678:24678" # Vite HMR
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

volumes:
  api_dev_cache:
    driver: local
  client_node_modules:
    driver: local

networks:
  default:
    name: monorepo-dev-network
